name: Bot Auto Tweet - RSS Feed

on:
  schedule:
    # Menjalankan setiap 1 jam sekali pada menit ke-5
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # --- TAMBAHKAN BLOK INI UNTUK MEMBERI IZIN MENULIS ---
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests beautifulsoup4 feedparser

      - name: Run RSS Bot
        run: python bot_rss.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain posted_rss_links.txt) ]]; then
            git add posted_rss_links.txt
            git commit -m "Update posted RSS links history"
            git push
            echo "✅ Riwayat link RSS telah diperbarui dan di-push ke repositori."
          else
            echo "✅ Tidak ada perubahan pada riwayat link, tidak perlu commit."
          fi
